### ISSUE TITLE
공식명칭은 함수형 컴포넌트가 아닌 함수 컴포넌트입니다

### ISSUE THREAD

**Issue by CraftyDragon678** [sangheon-kim/React-docs-analyze#1]
https://github.com/reactjs/reactjs.org/pull/863
여기 PR을 보면 예전에는 함수형 컴포넌트(functional component)라고 불렸지만, 지금은 함수 컴포넌트(function component)라고 부릅니다.

분석글인만큼 공식 문서에 있는 표현을 사용했으면 좋겠습니다.

**Comment by sangheon-kim** [comment]
피드백 감사합니다 바로 수정해서 푸시했습니다!

**Comment by sangheon-kim** [comment]
반영 완료하여 클로즈했습니다
